language: c
sudo: required

env:
  - BUILD_TARGET=3.7
#  - BUILD_TARGET=3.6
#  - BUILD_TARGET=2.7

os:
  - linux
#  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set anaconda_upload no
  - conda update --yes -q conda
  - export LANG=en_US.UTF-8

install:
  - conda install -q python=$BUILD_TARGET pip conda-build anaconda-client conda-verify

script:
  - conda build crc32c --python=$BUILD_TARGET

deploy:
  - provider: script
    script: bash deploy_anaconda.sh
    on:
      branch: master
      #tags: true
    skip_cleanup: true